fix(crds/dbuser): Add missing kind property
db-operator/charts pull request #32
Opened 2023-12-29 14:54 UTC by hcnp

This can make the helm-controller in FluxCD fail wihen deploying the CRDs.

It looks like it was removed by mistake in this commit: https://github.com/db-operator/charts/pull/31/files#diff-66962a372944a921e46f640964fc4b5b1a70be183156b5c8e2da609b6700b110L57

2024-01-02 13:20 UTC, hcnp commented
@allanger: Do I need to tag someone like this, or how does it work?

2024-01-02 14:11 UTC, allanger commented
@hcnp  
I'll have a look

2024-01-02 14:18 UTC, allanger commented
> Do I need to tag someone like this, or how does it work?
You can always tag me, or I'll eventually bump on the PR in my github feed, but tagging directly is faster. 

Usually, I'm tagging other maintainers myself when I need help. Currently, it works like that :)

2024-01-02 14:26 UTC, hcnp commented
Thats cool. I was just unsure if anyone would see the PR eventually ;)

2024-01-02 14:46 UTC, allanger requested changes
Could you please change the db-operator chart version to 1.16.2?

2024-01-03 15:59 UTC, allanger commented
I've merged my pr with the same change, because we already have an issue from another user and I guess it should be fixed rather fast. https://github.com/db-operator/charts/pull/37
I'm sorry for stealing your contribution

2024-01-03 15:59 UTC, closed without merging

2024-01-03 16:06 UTC, hcnp commented
> I've merged my pr with the same change, because we already have an issue from another user and I guess it should be fixed rather fast. #37 I'm sorry for stealing your contribution

Thanks!